accounts/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # url(r"login/$", views.LoginView.as_view(), name="login")
    url(r"logout/$", views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup")
]

todo_site/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers

from todos import api_v2_views

router = routers.SimpleRouter()
router.register(r"todo_lists", api_v2_views.TodoListViewSet)


urlpatterns = [
    url(r"^todos/", include("todos.urls", namespace="todos"),),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^api/v1/", include("todos.api_v1_urls", namespace="apiv1"),),
    url(r"^api/v2/", include(router.urls, namespace="apiv2"),),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

todos/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.TodoListListView.as_view(), name="todo_list_overview"),
    url(r"^(?P<pk>\d+)/$", views.TodoListDetailView.as_view(), name="todo_list"),
    url(r"^(?P<todo_list_pk>\d+)/edit_todo_list/$", views.todo_list_edit, name="edit_todo_list"),
    url(r"^(?P<pk>\d+)/delete_todo_list/$", views.TodoListDeleteView.as_view(), name="delete_todo_list")
    ,
    url(r"^(?P<todo_list_pk>\d+)/create_item/$", views.item_create, name="create_item"),
    url(r"^(?P<todo_list_pk>\d+)/(?P<item_pk>\d+)/$", views.item_detail, name="item"),
    url(r"^(?P<todo_list_pk>\d+)/edit_item/(?P<item_pk>\d+)/$", views.item_edit, name="edit_item"),
]

accounts/models.py
from django.db import models

# Create your models here.

todos/models.py
from django.core.urlresolvers import reverse
from django.db import models


class TodoList(models.Model):
    name = models.CharField(max_length=60)
    created_at = models.DateTimeField(auto_now_add=True)
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ["order",]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("todos:todo_list", kwargs={
            "pk": self.pk,
        })


class Item(models.Model):
    name = models.CharField(max_length=60)
    description = models.TextField(default="")
    created_at = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)
    order = models.IntegerField(default=0)
    todo_list = models.ForeignKey(TodoList)

    class Meta:
        ordering = ["order",]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("todos:item", kwargs={
            "todo_list_pk": self.todo_list.pk,
            "item_pk": self.pk
        })

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

todos/forms.py
from django import forms

from . import models

class TodoListForm(forms.ModelForm):
    class Meta:
        model = models.TodoList
        fields = ["name", "order"]


class ItemForm(forms.ModelForm):
    class Meta:
        model = models.Item
        fields = ["name", "description", "order", "completed"]

ItemFormSet = forms.modelformset_factory(
    models.Item,
    form = ItemForm,
)

accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.urlresolvers import reverse_lazy
from django.views import generic

from accounts.forms import UserCreateForm


class LoginView(generic.FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy("todos:todo_list_overview")
    template_name = "accounts/login.html"

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
            return form_class(self.request, **self.get_form_kwargs())

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)

class LogoutView(generic.RedirectView):
    url = reverse_lazy("todos:todo_list_overview")

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)

class SignUp(generic.CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

todos/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, DetailView,
    CreateView, UpdateView, DeleteView
)

from .forms import ItemForm, TodoListForm
from .mixins import PageTitleMixin
from .models import Item, TodoList

# Class based views
class TodoListListView(CreateView, ListView):
    model = TodoList
    context_object_name = "todo_lists"
    fields = ("name",)
    template_name = "todos/todo_list_overview.html"

    def form_valid(self, form):
        if  not self.request.user.is_authenticated:
            return HttpResponseForbidden()
        return super().form_valid(form)

class TodoListDetailView(PageTitleMixin, UpdateView, DetailView):
    fields = ("name", "order")
    model = TodoList
    context_object_name = "todo_list"
    template_name = "todos/todo_list_detail.html"

    def get_page_title(self):
        obj = self.get_object()
        return "{} Details".format(obj.name)

    def form_valid(self, form):
        if  not self.request.user.is_authenticated:
            return HttpResponseForbidden()
        return super().form_valid(form)

class TodoListDeleteView(LoginRequiredMixin, DeleteView):
    model = TodoList
    template_name = "todos/todo_list_confirm_delete.html"
    success_url = reverse_lazy("todos:todo_list_overview")


# Function views

# def todo_list_overview(request):
#     todo_lists = TodoList.objects.all()
#     total = todo_lists.aggregate(total=Count("name"))
#     return render(request, "todos/todo_list_overview.html", {"todo_lists": todo_lists, "total": total})

# def todo_list_detail(request, todo_list_pk):
#     todo_list = get_object_or_404(TodoList, pk=todo_list_pk)
#     return render(request, "todos/todo_list_detail.html", {"todo_list": todo_list})

def todo_list_edit(request, todo_list_pk):
    todo_list = get_object_or_404(TodoList, pk=todo_list_pk)
    form = TodoListForm(instance=todo_list)

    if request.method == "POST":
        form = TodoListForm(instance=todo_list, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Created {}".format(form.cleaned_data["name"]))
            return HttpResponseRedirect(todo_list.get_absolute_url())

    return render(request, "todos/todo_list_form.html", {"form": form, "todo_list": todo_list})

def item_detail(request, todo_list_pk, item_pk):
    item = get_object_or_404(Item, todo_list_id=todo_list_pk, pk=item_pk)
    return render(request, "todos/item_detail.html", {"item": item})

@login_required
def item_create(request, todo_list_pk):
    todo_list = get_object_or_404(TodoList, pk=todo_list_pk)
    form = ItemForm()

    if request.method == "POST":
        form = ItemForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.todo_list = todo_list
            item.save()
            return HttpResponseRedirect(item.get_absolute_url())

    return render(request, "todos/item_form.html", {"form": form, "todo_list": todo_list})

@login_required
def item_edit(request, item_pk, todo_list_pk):
    item = get_object_or_404(Item, pk=item_pk, todo_list_id=todo_list_pk)
    form = ItemForm(instance=item)

    if request.method == "POST":
        form = ItemForm(instance=item, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated {}".format(form.cleaned_data["name"]))
            return HttpResponseRedirect(item.get_absolute_url())

    return render(request, "todos/item_form.html", {"item": item, "form": form, "todo_list": item.todo_list})

accounts/templates/accounts/signup.html
{% extends "layout.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <h1>Sign Up</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Sign up">
    </form>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}"/>
</head>
<body>
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
    <a href="{% url "todos:todo_list_overview" %}">Overview</a>
    {% if not user.is_authenticated %}
        <a href="{% url "login" %}">Login</a>
        <a href="{% url "accounts:signup" %}">Sign up</a>
    {% else %}
        <a href="{% url "logout" %}">Logout</a>
    {% endif %}
{% block content %} {% endblock %}
</body>
</html>

todos/templates/todos/item_detail.html
{% extends "layout.html" %}

{% block title %}{{ item.todo_list.name }} - {{ item.name }}{% endblock %}

{% block content %}
    <h3><a href="{% url 'todos:todo_list' pk=item.todo_list.pk %}">{{ item.todo_list.name }}</a></h3>

    <h2>{{ item.name }}</h2>
    <p>{{ item.description }}</p>

    {% if user.is_authenticated %}
        <a href="{% url 'todos:edit_item' todo_list_pk=item.todo_list.pk item_pk=item.pk%}">Edit</a>
    {% endif %}
{% endblock %}

todos/templates/todos/item_form.html
{% extends "layout.html" %}

{% block title %}Create an Item{% endblock %}

{% block content %}
    <h2>{{ item|default:"Create an Item"}}</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

todos/templates/todos/todo_list_confirm_delete.html
{% extends "layout.html" %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock %}

todos/templates/todos/todo_list_detail.html
{% extends "layout.html" %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <h2>{{ todo_list.name }}</h2>
    <ul>
        {% for item in todo_list.item_set.all %}
            <li>
                <a href="{% url 'todos:item' todo_list_pk=todo_list.pk item_pk=item.pk %}">{{ item.name }}</a>
                {{ item.created_at }}
                {% if item.completed %}
                    <input type="checkbox" checked="checked" disabled="disabled"/>
                {% else %}
                    <input type="checkbox" disabled="disabled"/>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    {% if user.is_authenticated %}
    <a href="{% url 'todos:create_item' todo_list_pk=todo_list.pk %}">New item</a>
    <br/>
        <form method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
        <br/>

        <a href="{% url 'todos:delete_todo_list' pk=todo_list.pk %}">Delete todo list</a>
    {% endif %}
{% endblock %}

todos/templates/todos/todo_list_form.html
{% extends "layout.html" %}

{% block title %}Create a Todo List{% endblock %}

{% block content %}
    <h2>Edit the Todo List</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

todos/templates/todos/todo_list_overview.html
{% extends "layout.html" %}

{% block title %}Todo Lists{% endblock %}

{% block content %}
    <h1>Todo Lists</h1>
    <p>There {{ total.total|pluralize:"is, are" }} {{ total.total }} todo list{{ total.total|pluralize }}</p>
    {% for todo_list in todo_lists  %}
        <p><a href="{% url 'todos:todo_list' pk=todo_list.pk%}">{{ todo_list.name }}</a></p>
        <p>created {{ todo_list.created_at }}</p>
    {% endfor %}
    {% if user.is_authenticated %}
        <div class="row">
            <form method='POST'>
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save">
            </form>
        </div>
    {% endif %}
{% endblock %}